name: Deploy

on:
  repository_dispatch:
    types: [published]

jobs:
  deploy:

    runs-on: ubuntu-20.04
    container: jshimko/kube-tools-aws:3.7.0

    env:
      flex: "./.flex/flex"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ENV: ${{ github.event.client_payload.env }}

    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: ./flex.sh
    - name: Deploy
      run: $flex deploy
